name: Build
on: [ push, workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Build project
        run: yarn run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: build-files
