name: Deploy React App
on: push
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Test application
        run: npm run test
      - name: lint application
        run: yarn run lint
      - name: Deploy
        run: echo Deploying ...