name: Test React App
on: push
jobs:
  test_my_here:
    runs-on: ubuntu-22.04
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Test application
        run: npm run test